name: Build docs

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  pages:
    runs-on:  ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[with-data,dev]
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        requirements_path: ./docs/doc_requirements.txt
