name: Run Evaluation

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install bib_dedupe package
        run: |
          pip install .
          pip install -r notebooks/requirements.txt

      - name: Run Evaluation
        run: |
          jupyter nbconvert --execute notebooks/evaluation.ipynb --to notebook --inplace

      - name: Commit and push changes
        run: |
          git config --global user.name "bib-dedupe evaluator"
          git config --global user.email "youremail@example.com"
          git add output/*
          git commit -m "Update evaluation ($(date +'%Y-%m-%d-%H-%M'))"
          git push origin main
