name: Run Evaluation

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cloc \
            gdal-bin \
            gdebi-core \
            git \
            libcurl4-openssl-dev \
            libgdal-dev \
            libproj-dev \
            libxml2-dev \
            ghostscript \
            imagemagick \
            xpdf \
            build-essential \
            libmysqlclient-dev \
            libsqlite3-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            pkg-config

      - name: Install Bundler and Gems
        run: |
          gem install bundler -v 2.3.27
          cd notebooks/buhos
          bundle install --verbose

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install uv and dependencies
        run: |
          pip install uv
          uv venv
          uv pip install -e .[with-data]
          echo "Dependencies installed successfully"

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      - name: Install ASySD with dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
          R -e 'install.packages(c("curl", "gert", "gh"))'
          R -e 'install.packages(c("usethis", "pkgdown", "rcmdcheck", "rversions", "urlchecker"))'
          R -e 'install.packages("devtools")'
          R -e 'devtools::install_github("camaradesuk/ASySD")'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Evaluation
        run: |
          uv run python notebooks/evaluation.py

      - name: Commit and push changes
        run: |
          git config --global user.name "bib-dedupe evaluator"
          git config --global user.email "youremail@example.com"
          git add output/*
          git add docs/_static/evaluation_total.png*
          git commit -m "Update evaluation ($(date +'%Y-%m-%d-%H-%M'))"
          git pull origin main --rebase
          git push origin main
